# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/final_constraints.xdc

# Block Designs: bd/final_block/final_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_block || ORIG_REF_NAME==final_block} -quiet] -quiet

# IP: bd/final_block/ip/final_block_processing_system7_0_0/final_block_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_block_processing_system7_0_0 || ORIG_REF_NAME==final_block_processing_system7_0_0} -quiet] -quiet

# IP: bd/final_block/ip/final_block_xadc_wiz_0_0/final_block_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_block_xadc_wiz_0_0 || ORIG_REF_NAME==final_block_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/final_block/ip/final_block_clk_wiz_0_0/final_block_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_block_clk_wiz_0_0 || ORIG_REF_NAME==final_block_clk_wiz_0_0} -quiet] -quiet

# IP: bd/final_block/ip/final_block_XADC_interpreter_2_0_0/final_block_XADC_interpreter_2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_block_XADC_interpreter_2_0_0 || ORIG_REF_NAME==final_block_XADC_interpreter_2_0_0} -quiet] -quiet

# IP: bd/final_block/ip/final_block_Top_level_0_1/final_block_Top_level_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_block_Top_level_0_1 || ORIG_REF_NAME==final_block_Top_level_0_1} -quiet] -quiet

# IP: bd/final_block/ip/final_block_axi_gpio_0_0/final_block_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_block_axi_gpio_0_0 || ORIG_REF_NAME==final_block_axi_gpio_0_0} -quiet] -quiet

# IP: bd/final_block/ip/final_block_xbar_0/final_block_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_block_xbar_0 || ORIG_REF_NAME==final_block_xbar_0} -quiet] -quiet

# IP: bd/final_block/ip/final_block_auto_pc_3/final_block_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_block_auto_pc_3 || ORIG_REF_NAME==final_block_auto_pc_3} -quiet] -quiet

# IP: bd/final_block/ip/final_block_auto_pc_4/final_block_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_block_auto_pc_4 || ORIG_REF_NAME==final_block_auto_pc_4} -quiet] -quiet

# IP: bd/final_block/ip/final_block_s00_mmu_0/final_block_s00_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_block_s00_mmu_0 || ORIG_REF_NAME==final_block_s00_mmu_0} -quiet] -quiet

# IP: bd/final_block/ip/final_block_s01_mmu_0/final_block_s01_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_block_s01_mmu_0 || ORIG_REF_NAME==final_block_s01_mmu_0} -quiet] -quiet

# IP: bd/final_block/ip/final_block_ps7_0_axi_periph_3/final_block_ps7_0_axi_periph_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_block_ps7_0_axi_periph_3 || ORIG_REF_NAME==final_block_ps7_0_axi_periph_3} -quiet] -quiet

# IP: bd/final_block/ip/final_block_rst_clk_wiz_0_40M_0/final_block_rst_clk_wiz_0_40M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_block_rst_clk_wiz_0_40M_0 || ORIG_REF_NAME==final_block_rst_clk_wiz_0_40M_0} -quiet] -quiet

# IP: bd/final_block/ip/final_block_axi_gpio_1_0/final_block_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==final_block_axi_gpio_1_0 || ORIG_REF_NAME==final_block_axi_gpio_1_0} -quiet] -quiet

# XDC: c:/Users/onwuxc/Desktop/Work/Final_project/Final_project.gen/sources_1/bd/final_block/ip/final_block_processing_system7_0_0/final_block_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==final_block_processing_system7_0_0 || ORIG_REF_NAME==final_block_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/onwuxc/Desktop/Work/Final_project/Final_project.gen/sources_1/bd/final_block/ip/final_block_xadc_wiz_0_0/final_block_xadc_wiz_0_0_ooc.xdc

# XDC: c:/Users/onwuxc/Desktop/Work/Final_project/Final_project.gen/sources_1/bd/final_block/ip/final_block_xadc_wiz_0_0/final_block_xadc_wiz_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==final_block_xadc_wiz_0_0 || ORIG_REF_NAME==final_block_xadc_wiz_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/onwuxc/Desktop/Work/Final_project/Final_project.gen/sources_1/bd/final_block/ip/final_block_clk_wiz_0_0/final_block_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==final_block_clk_wiz_0_0 || ORIG_REF_NAME==final_block_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/onwuxc/Desktop/Work/Final_project/Final_project.gen/sources_1/bd/final_block/ip/final_block_clk_wiz_0_0/final_block_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==final_block_clk_wiz_0_0 || ORIG_REF_NAME==final_block_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/onwuxc/Desktop/Work/Final_project/Final_project.gen/sources_1/bd/final_block/ip/final_block_clk_wiz_0_0/final_block_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/onwuxc/Desktop/Work/Final_project/Final_project.gen/sources_1/bd/final_block/ip/final_block_axi_gpio_0_0/final_block_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==final_block_axi_gpio_0_0 || ORIG_REF_NAME==final_block_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/onwuxc/Desktop/Work/Final_project/Final_project.gen/sources_1/bd/final_block/ip/final_block_axi_gpio_0_0/final_block_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/onwuxc/Desktop/Work/Final_project/Final_project.gen/sources_1/bd/final_block/ip/final_block_axi_gpio_0_0/final_block_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==final_block_axi_gpio_0_0 || ORIG_REF_NAME==final_block_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/onwuxc/Desktop/Work/Final_project/Final_project.gen/sources_1/bd/final_block/ip/final_block_auto_pc_3/final_block_auto_pc_3_ooc.xdc

# XDC: c:/Users/onwuxc/Desktop/Work/Final_project/Final_project.gen/sources_1/bd/final_block/ip/final_block_auto_pc_4/final_block_auto_pc_4_ooc.xdc

# XDC: c:/Users/onwuxc/Desktop/Work/Final_project/Final_project.gen/sources_1/bd/final_block/ip/final_block_rst_clk_wiz_0_40M_0/final_block_rst_clk_wiz_0_40M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==final_block_rst_clk_wiz_0_40M_0 || ORIG_REF_NAME==final_block_rst_clk_wiz_0_40M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/onwuxc/Desktop/Work/Final_project/Final_project.gen/sources_1/bd/final_block/ip/final_block_rst_clk_wiz_0_40M_0/final_block_rst_clk_wiz_0_40M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==final_block_rst_clk_wiz_0_40M_0 || ORIG_REF_NAME==final_block_rst_clk_wiz_0_40M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/onwuxc/Desktop/Work/Final_project/Final_project.gen/sources_1/bd/final_block/ip/final_block_axi_gpio_1_0/final_block_axi_gpio_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==final_block_axi_gpio_1_0 || ORIG_REF_NAME==final_block_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/onwuxc/Desktop/Work/Final_project/Final_project.gen/sources_1/bd/final_block/ip/final_block_axi_gpio_1_0/final_block_axi_gpio_1_0_ooc.xdc

# XDC: c:/Users/onwuxc/Desktop/Work/Final_project/Final_project.gen/sources_1/bd/final_block/ip/final_block_axi_gpio_1_0/final_block_axi_gpio_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==final_block_axi_gpio_1_0 || ORIG_REF_NAME==final_block_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/onwuxc/Desktop/Work/Final_project/Final_project.gen/sources_1/bd/final_block/final_block_ooc.xdc
