domain_path: C:\Users\onwuxc\Desktop\Work\Final_project_SW\Biosensor_FGPA\export\Biosensor_FGPA\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx2\Vitis\2024.1\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
